### ISSUE TITLE
Video preview

### ISSUE THREAD

**Issue by SamDecrock** [citolen/goproh4#6]
Hi,

have you had any success on retrieving a live video feed?

Grtz,
Sam

**Comment by citolen** [comment]
Hey Sam,

Yes, here are the steps:

1. Connect to your GoPro's wifi.
2. Open [http://10.5.5.9/gp/gpControl/execute?p1=gpStream&c1=restart](http://10.5.5.9/gp/gpControl/execute?p1=gpStream&c1=restart).
3. Launch [this](https://gist.github.com/nmrony/cb5db4093b4033526720) python script, basicaly it's sending \_GPHD\_:0:0:2:0.000000 to 10.5.5.9:8554 using udp, this is to tell the gopro to keep streaming otherwise it will stop after a couple of seconds.
4. Open the stream, I have been able to do that using ffplay like this:
```
ffplay udp://10.5.5.9:8554 -f mpegts -fflags nobuffer
```
You may have to wait a few seconds before ffplay shows the stream, I'm not sure why but it is probably because it needs a few frames to be able to tell the stream details (resolution, fps,...).

I hope this can help you.

Cheers,
Nils
